fix: Remove duplicate service implementations causing Spring bean conflicts
Deleted old service implementations that conflicted with new integration/* structure:
- service/confluence/WikiService.kt (duplicate of integration/wiki/WikiService.kt)
- service/confluence/WikiServiceImpl.kt (duplicate of integration/wiki/internal/WikiServiceImpl.kt)
- service/jira/BugTrackerService.kt (duplicate of integration/bugtracker/BugTrackerService.kt)
- service/jira/JiraServiceImpl.kt (duplicate of integration/bugtracker/internal/BugTrackerServiceImpl.kt)

Also cleaned up empty directories:
- entity/confluence/ and entity/jira/
- service/indexing/jira/ and service/indexing/confluence/
- service/polling/handler/bugtracker/ and service/polling/handler/documentation/

Fixes Spring startup error:
ConflictingBeanDefinitionException: bean name 'wikiServiceImpl' conflicts

Server now starts successfully.